server:
  port: 9411
spring:
  application:
    name: kirin-zipkin-server
  main:
    # 当bean重复定义时允许相同key情况下beanDefinition实例的覆盖
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false