spring:
  zipkin:
    base-url: http://localhost:9411

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: admin
    username: admin

server:
  port: 8882

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
