server:
  port: 8900

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: admin
    username: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"