server:
  port: 8200

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/kirin-user?serverTimezone=GMT%2B8
    username: root
    password: 831015
    hikari:
      # 最小空闲数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池母子
      pool-name: MyHikariCP
      # 池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试sql
      connection-test-query: SELECT 1
      read-only: false
  # redis配置
  redis:
    # 数据库索引
    database: 2
    # redis服务器地址
    host: 127.0.0.1
    # 端口
    port: 6379
    # 连接超时时间
    timeout: 1000
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mappers/**/*.xml
