spring:
  application:
    name: product-data-service

  zipkin:
    base-url: http://localhost:9411

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    refresh:
      enabled: false