spring:
  application:
    name: product-data-service

  zipkin:
    base-url: http://localhost:9411

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    refresh:
      enabled: false

# 日志
logging:
  file: D:/log/dataServer/data-server.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
