server:
  port: 8100
spring:
  redis:
    # 数据库索引
    database: 1
    # redis服务器地址
    host: 127.0.0.1
    # 端口
    port: 6379
    # 连接超时时间
    timeout: 1000
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0